baseURL: https://starscope.netlify.app/
relativeURLs: yes
uglyURLs: no
theme: hugo-theme-relearn
defaultContentLanguage: en
title: StarScope
summaryLength: 10
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
outputs:
  home:
    - html
    - rss
    - print
    - search
    - searchpage
  page:
    - html
    - rss
    - print
  section:
    - html
    - rss
    - print
markup:
  goldmark:
    duplicateResourceFiles: yes
    extensions:
      passthrough:
        delimiters:
          block:
            - - \[
              - \]
            - - $$
              - $$
          inline:
            - - \(
              - \)
            - - $
              - $
        enable: yes
    renderer:
      unsafe: yes
  highlight:
    lineNumbersInTable: no
    noClasses: no
languages:
  en:
    languageName: English
    languageCode: en-us
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fa-fw fab fa-github'></i> GitHub repo
          url: https://github.com/obenno/StarScope
          weight: 10
        - name: <i class='fa-fw fas fa-tags'></i> Tags
          pageRef: tags/
          weight: 40
        - name: <i class='fa-fw fas fa-layer-group'></i> Categories
          pageRef: categories/
          weight: 50
    params:
      landingPageName: <i class='fa-fw fas fa-home'></i> Home
    title: StarScope
    weight: 1
module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: content
      target: content
    - source: data
      target: data
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
    - source: static
      target: static
    - source: config
      target: assets/config
    - source: ../images
      target: assets/images
    - source: ../CHANGELOG.md
      target: assets/CHANGELOG.md
    - source: ../README.md
      target: assets/README.md
services:
  googleAnalytics:
    ID: G-D141RBHZJ9
params:
  siteparam:
    test:
      text: A **nested** option <b>with</b> formatting
