# modified from https://github.com/pytorch/pytorch/blob/main/.github/workflows/create_release.yml
name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: ${{ github.repository == 'obenno/StarScope' }}
    name: Create Release
    runs-on: ubuntu-latest
    # https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - name: Fake name for PRs
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "SC_GITHUB_REF=refs/tags/pr-tag" >> "$GITHUB_ENV"
      - name: Real name for non-PRs
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "SC_GITHUB_REF=$GITHUB_REF" >> "$GITHUB_ENV"
      - name: Set filenames
        run: |
          tag_or_branch="${SC_GITHUB_REF#refs/tags/}"
          tag_or_branch="${tag_or_branch#refs/heads/}"
          # replace directory separators with _ in branch name
          tag_or_branch="${tag_or_branch//\//_}"
          echo "SC_RELEASE_NAME=starscope-$tag_or_branch" >> "$GITHUB_ENV"
          echo "SC_RELEASE_FILE=starscope-$tag_or_branch.tar.gz" >> "$GITHUB_ENV"
      - name: Create source distribution
        run: |
            # Create new folder with specified name so extracting the archive yields that
            rm -rf "/tmp/$SC_RELEASE_NAME"
            cp -r "$PWD" "/tmp/$SC_RELEASE_NAME"
            mv "/tmp/$SC_RELEASE_NAME" .
            # Cleanup
            rm -rf "$SC_RELEASE_NAME"/{.circleci,.ci}
            find "$SC_RELEASE_NAME" -name '.git*' -exec rm -rv {} \; || true
            # Create archive
            tar -czf "$SC_RELEASE_FILE" "$SC_RELEASE_NAME"
            echo "Created source archive $SC_RELEASE_FILE with content: $(ls -a "$SC_RELEASE_NAME")"
      - name: Upload source distribution
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{env.SC_RELEASE_FILE}}
